defaults: &defaults
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["DB_USERNAME"] || "postgres" %>
  password: <%= ENV["DB_PASSWORD"] || "1234" %>
  timeout: 5000
  pool: 20
  host: localhost
  port: 5432

development:
  database: kodep_dev
  <<: *defaults
